// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/Match.proto
// Protobuf C++ Version: 6.32.0

#include "proto/Match.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr NewMatchResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        gamecode_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NewMatchResponse::NewMatchResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NewMatchResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NewMatchResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NewMatchResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NewMatchResponseDefaultTypeInternal() {}
  union {
    NewMatchResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NewMatchResponseDefaultTypeInternal _NewMatchResponse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR NewMatchRequest::NewMatchRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(NewMatchRequest_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct NewMatchRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NewMatchRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NewMatchRequestDefaultTypeInternal() {}
  union {
    NewMatchRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NewMatchRequestDefaultTypeInternal _NewMatchRequest_default_instance_;

inline constexpr NewMatchInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        gamecode_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NewMatchInfo::NewMatchInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NewMatchInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NewMatchInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NewMatchInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NewMatchInfoDefaultTypeInternal() {}
  union {
    NewMatchInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NewMatchInfoDefaultTypeInternal _NewMatchInfo_default_instance_;

inline constexpr Wrapper::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Wrapper::Wrapper(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Wrapper_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WrapperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WrapperDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WrapperDefaultTypeInternal() {}
  union {
    Wrapper _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WrapperDefaultTypeInternal _Wrapper_default_instance_;
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_proto_2fMatch_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2fMatch_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2fMatch_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::Wrapper, _impl_._oneof_case_[0]),
        PROTOBUF_FIELD_OFFSET(::Wrapper, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::Wrapper, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::Wrapper, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::Wrapper, _impl_.payload_),
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::NewMatchInfo, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::NewMatchInfo, _impl_.gamecode_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::NewMatchResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::NewMatchResponse, _impl_.gamecode_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Wrapper)},
        {6, sizeof(::NewMatchRequest)},
        {7, sizeof(::NewMatchInfo)},
        {12, sizeof(::NewMatchResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_Wrapper_default_instance_._instance,
    &::_NewMatchRequest_default_instance_._instance,
    &::_NewMatchInfo_default_instance_._instance,
    &::_NewMatchResponse_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fMatch_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021proto/Match.proto\"}\n\007Wrapper\022\"\n\006matReq"
    "\030\001 \001(\0132\020.NewMatchRequestH\000\022\036\n\005matIn\030\002 \001("
    "\0132\r.NewMatchInfoH\000\022#\n\006matRes\030\003 \001(\0132\021.New"
    "MatchResponseH\000B\t\n\007payload\"\021\n\017NewMatchRe"
    "quest\" \n\014NewMatchInfo\022\020\n\010gameCode\030\001 \001(\005\""
    "$\n\020NewMatchResponse\022\020\n\010gameCode\030\001 \001(\005b\006p"
    "roto3"
};
static ::absl::once_flag descriptor_table_proto_2fMatch_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2fMatch_2eproto = {
    false,
    false,
    245,
    descriptor_table_protodef_proto_2fMatch_2eproto,
    "proto/Match.proto",
    &descriptor_table_proto_2fMatch_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_proto_2fMatch_2eproto::offsets,
    file_level_enum_descriptors_proto_2fMatch_2eproto,
    file_level_service_descriptors_proto_2fMatch_2eproto,
};
// ===================================================================

class Wrapper::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Wrapper, _impl_._oneof_case_);
};

void Wrapper::set_allocated_matreq(::NewMatchRequest* PROTOBUF_NULLABLE matreq) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (matreq) {
    ::google::protobuf::Arena* submessage_arena = matreq->GetArena();
    if (message_arena != submessage_arena) {
      matreq = ::google::protobuf::internal::GetOwnedMessage(message_arena, matreq, submessage_arena);
    }
    set_has_matreq();
    _impl_.payload_.matreq_ = matreq;
  }
  // @@protoc_insertion_point(field_set_allocated:Wrapper.matReq)
}
void Wrapper::set_allocated_matin(::NewMatchInfo* PROTOBUF_NULLABLE matin) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (matin) {
    ::google::protobuf::Arena* submessage_arena = matin->GetArena();
    if (message_arena != submessage_arena) {
      matin = ::google::protobuf::internal::GetOwnedMessage(message_arena, matin, submessage_arena);
    }
    set_has_matin();
    _impl_.payload_.matin_ = matin;
  }
  // @@protoc_insertion_point(field_set_allocated:Wrapper.matIn)
}
void Wrapper::set_allocated_matres(::NewMatchResponse* PROTOBUF_NULLABLE matres) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (matres) {
    ::google::protobuf::Arena* submessage_arena = matres->GetArena();
    if (message_arena != submessage_arena) {
      matres = ::google::protobuf::internal::GetOwnedMessage(message_arena, matres, submessage_arena);
    }
    set_has_matres();
    _impl_.payload_.matres_ = matres;
  }
  // @@protoc_insertion_point(field_set_allocated:Wrapper.matRes)
}
Wrapper::Wrapper(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Wrapper_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Wrapper)
}
PROTOBUF_NDEBUG_INLINE Wrapper::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Wrapper& from_msg)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Wrapper::Wrapper(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Wrapper& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Wrapper_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Wrapper* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kMatReq:
        _impl_.payload_.matreq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.matreq_);
        break;
      case kMatIn:
        _impl_.payload_.matin_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.matin_);
        break;
      case kMatRes:
        _impl_.payload_.matres_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.matres_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Wrapper)
}
PROTOBUF_NDEBUG_INLINE Wrapper::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Wrapper::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Wrapper::~Wrapper() {
  // @@protoc_insertion_point(destructor:Wrapper)
  SharedDtor(*this);
}
inline void Wrapper::SharedDtor(MessageLite& self) {
  Wrapper& this_ = static_cast<Wrapper&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void Wrapper::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:Wrapper)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kMatReq: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.matreq_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.matreq_);
      }
      break;
    }
    case kMatIn: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.matin_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.matin_);
      }
      break;
    }
    case kMatRes: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.matres_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.matres_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* PROTOBUF_NONNULL Wrapper::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Wrapper(arena);
}
constexpr auto Wrapper::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Wrapper),
                                            alignof(Wrapper));
}
constexpr auto Wrapper::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Wrapper_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Wrapper::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Wrapper>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Wrapper::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Wrapper>(), &Wrapper::ByteSizeLong,
              &Wrapper::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Wrapper, _impl_._cached_size_),
          false,
      },
      &Wrapper::kDescriptorMethods,
      &descriptor_table_proto_2fMatch_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Wrapper_class_data_ =
        Wrapper::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Wrapper::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Wrapper_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Wrapper_class_data_.tc_table);
  return Wrapper_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 3, 0, 2>
Wrapper::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Wrapper_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Wrapper>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .NewMatchRequest matReq = 1;
    {PROTOBUF_FIELD_OFFSET(Wrapper, _impl_.payload_.matreq_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .NewMatchInfo matIn = 2;
    {PROTOBUF_FIELD_OFFSET(Wrapper, _impl_.payload_.matin_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .NewMatchResponse matRes = 3;
    {PROTOBUF_FIELD_OFFSET(Wrapper, _impl_.payload_.matres_), _Internal::kOneofCaseOffset + 0, 2, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::NewMatchRequest>()},
      {::_pbi::TcParser::GetTable<::NewMatchInfo>()},
      {::_pbi::TcParser::GetTable<::NewMatchResponse>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Wrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:Wrapper)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Wrapper::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Wrapper& this_ = static_cast<const Wrapper&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Wrapper::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Wrapper& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Wrapper)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.payload_case()) {
    case kMatReq: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, *this_._impl_.payload_.matreq_, this_._impl_.payload_.matreq_->GetCachedSize(), target,
          stream);
      break;
    }
    case kMatIn: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.payload_.matin_, this_._impl_.payload_.matin_->GetCachedSize(), target,
          stream);
      break;
    }
    case kMatRes: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *this_._impl_.payload_.matres_, this_._impl_.payload_.matres_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Wrapper)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Wrapper::ByteSizeLong(const MessageLite& base) {
  const Wrapper& this_ = static_cast<const Wrapper&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Wrapper::ByteSizeLong() const {
  const Wrapper& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Wrapper)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.payload_case()) {
    // .NewMatchRequest matReq = 1;
    case kMatReq: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.matreq_);
      break;
    }
    // .NewMatchInfo matIn = 2;
    case kMatIn: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.matin_);
      break;
    }
    // .NewMatchResponse matRes = 3;
    case kMatRes: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.matres_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Wrapper::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Wrapper*>(&to_msg);
  auto& from = static_cast<const Wrapper&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Wrapper)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kMatReq: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.matreq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.matreq_);
        } else {
          _this->_impl_.payload_.matreq_->MergeFrom(*from._impl_.payload_.matreq_);
        }
        break;
      }
      case kMatIn: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.matin_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.matin_);
        } else {
          _this->_impl_.payload_.matin_->MergeFrom(*from._impl_.payload_.matin_);
        }
        break;
      }
      case kMatRes: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.matres_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.matres_);
        } else {
          _this->_impl_.payload_.matres_->MergeFrom(*from._impl_.payload_.matres_);
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Wrapper::CopyFrom(const Wrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Wrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Wrapper::InternalSwap(Wrapper* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Wrapper::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NewMatchRequest::_Internal {
 public:
};

NewMatchRequest::NewMatchRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, NewMatchRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:NewMatchRequest)
}
NewMatchRequest::NewMatchRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NewMatchRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, NewMatchRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NewMatchRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:NewMatchRequest)
}

inline void* PROTOBUF_NONNULL NewMatchRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NewMatchRequest(arena);
}
constexpr auto NewMatchRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NewMatchRequest),
                                            alignof(NewMatchRequest));
}
constexpr auto NewMatchRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NewMatchRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NewMatchRequest::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<NewMatchRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NewMatchRequest::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<NewMatchRequest>(), &NewMatchRequest::ByteSizeLong,
              &NewMatchRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NewMatchRequest, _impl_._cached_size_),
          false,
      },
      &NewMatchRequest::kDescriptorMethods,
      &descriptor_table_proto_2fMatch_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NewMatchRequest_class_data_ =
        NewMatchRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NewMatchRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NewMatchRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NewMatchRequest_class_data_.tc_table);
  return NewMatchRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
NewMatchRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NewMatchRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NewMatchRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata NewMatchRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NewMatchInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NewMatchInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NewMatchInfo, _impl_._has_bits_);
};

NewMatchInfo::NewMatchInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NewMatchInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NewMatchInfo)
}
NewMatchInfo::NewMatchInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NewMatchInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NewMatchInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE NewMatchInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void NewMatchInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.gamecode_ = {};
}
NewMatchInfo::~NewMatchInfo() {
  // @@protoc_insertion_point(destructor:NewMatchInfo)
  SharedDtor(*this);
}
inline void NewMatchInfo::SharedDtor(MessageLite& self) {
  NewMatchInfo& this_ = static_cast<NewMatchInfo&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NewMatchInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NewMatchInfo(arena);
}
constexpr auto NewMatchInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NewMatchInfo),
                                            alignof(NewMatchInfo));
}
constexpr auto NewMatchInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NewMatchInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NewMatchInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NewMatchInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NewMatchInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NewMatchInfo>(), &NewMatchInfo::ByteSizeLong,
              &NewMatchInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NewMatchInfo, _impl_._cached_size_),
          false,
      },
      &NewMatchInfo::kDescriptorMethods,
      &descriptor_table_proto_2fMatch_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NewMatchInfo_class_data_ =
        NewMatchInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NewMatchInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NewMatchInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NewMatchInfo_class_data_.tc_table);
  return NewMatchInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
NewMatchInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NewMatchInfo, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NewMatchInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NewMatchInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 gameCode = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NewMatchInfo, _impl_.gamecode_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(NewMatchInfo, _impl_.gamecode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 gameCode = 1;
    {PROTOBUF_FIELD_OFFSET(NewMatchInfo, _impl_.gamecode_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void NewMatchInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:NewMatchInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.gamecode_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NewMatchInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NewMatchInfo& this_ = static_cast<const NewMatchInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NewMatchInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NewMatchInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:NewMatchInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 gameCode = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_gamecode() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_gamecode(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NewMatchInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NewMatchInfo::ByteSizeLong(const MessageLite& base) {
  const NewMatchInfo& this_ = static_cast<const NewMatchInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NewMatchInfo::ByteSizeLong() const {
  const NewMatchInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:NewMatchInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 gameCode = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_gamecode() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_gamecode());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NewMatchInfo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NewMatchInfo*>(&to_msg);
  auto& from = static_cast<const NewMatchInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:NewMatchInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (from._internal_gamecode() != 0) {
      _this->_impl_.gamecode_ = from._impl_.gamecode_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NewMatchInfo::CopyFrom(const NewMatchInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NewMatchInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NewMatchInfo::InternalSwap(NewMatchInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.gamecode_, other->_impl_.gamecode_);
}

::google::protobuf::Metadata NewMatchInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NewMatchResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NewMatchResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NewMatchResponse, _impl_._has_bits_);
};

NewMatchResponse::NewMatchResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NewMatchResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NewMatchResponse)
}
NewMatchResponse::NewMatchResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NewMatchResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NewMatchResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE NewMatchResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void NewMatchResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.gamecode_ = {};
}
NewMatchResponse::~NewMatchResponse() {
  // @@protoc_insertion_point(destructor:NewMatchResponse)
  SharedDtor(*this);
}
inline void NewMatchResponse::SharedDtor(MessageLite& self) {
  NewMatchResponse& this_ = static_cast<NewMatchResponse&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NewMatchResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NewMatchResponse(arena);
}
constexpr auto NewMatchResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(NewMatchResponse),
                                            alignof(NewMatchResponse));
}
constexpr auto NewMatchResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NewMatchResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &NewMatchResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NewMatchResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NewMatchResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NewMatchResponse>(), &NewMatchResponse::ByteSizeLong,
              &NewMatchResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NewMatchResponse, _impl_._cached_size_),
          false,
      },
      &NewMatchResponse::kDescriptorMethods,
      &descriptor_table_proto_2fMatch_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NewMatchResponse_class_data_ =
        NewMatchResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NewMatchResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NewMatchResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NewMatchResponse_class_data_.tc_table);
  return NewMatchResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
NewMatchResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NewMatchResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NewMatchResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NewMatchResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 gameCode = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NewMatchResponse, _impl_.gamecode_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(NewMatchResponse, _impl_.gamecode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 gameCode = 1;
    {PROTOBUF_FIELD_OFFSET(NewMatchResponse, _impl_.gamecode_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void NewMatchResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:NewMatchResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.gamecode_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NewMatchResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NewMatchResponse& this_ = static_cast<const NewMatchResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NewMatchResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NewMatchResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:NewMatchResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 gameCode = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_gamecode() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_gamecode(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NewMatchResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NewMatchResponse::ByteSizeLong(const MessageLite& base) {
  const NewMatchResponse& this_ = static_cast<const NewMatchResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NewMatchResponse::ByteSizeLong() const {
  const NewMatchResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:NewMatchResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 gameCode = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_gamecode() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_gamecode());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NewMatchResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NewMatchResponse*>(&to_msg);
  auto& from = static_cast<const NewMatchResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:NewMatchResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (from._internal_gamecode() != 0) {
      _this->_impl_.gamecode_ = from._impl_.gamecode_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NewMatchResponse::CopyFrom(const NewMatchResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NewMatchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NewMatchResponse::InternalSwap(NewMatchResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.gamecode_, other->_impl_.gamecode_);
}

::google::protobuf::Metadata NewMatchResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2fMatch_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
